name: Familie Merten 
markdown: kramdown
highlighter: rouge # pygments or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
permalink: /:year/:month/:day/:title:output_ext/index.html
themeBGimage: https://template.pc-cdn.de/assetss/bg-images/2009_03_29Colocasia_esculenta467.jpg
